name: code linter

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    code_linting:
        name: python code linting check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install flake8
              run: |
                  python -m pip install flake8
            - name: Lint code
              run: |
                  flake8 ./core

    terraform:
        name: terraform lint, security check and deploy
        runs-on: ubuntu-latest

        env:
            AWS_REGION: 'us-east-1'
            TF_VERSION: '1.4.0'
            TFLINT_VERSION: '0.46.1'
            TFSEC_VERSION: '1.28.1'
        steps:
            - name: checkout to gthub repo
              uses: actions/checkout@v2

            - name: Set up AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}
            - name: setup  terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ env.TF_VERSION}}

            - name: format Terraform files
              id: fmt_recursive
              run: terraform fmt -recursive
            - name: Terraform format
              id: fmt
              run: terraform fmt -check

            - name: Terraform Init
              id: init
              run: terraform init

            - name: Terraform Validate
              id: validate
              run: terraform validate -no-color

            - name: Terraform Plan
              id: plan
              run: terraform plan -no-color  -out=tfplan

            - name: Terraform Apply
              run: terraform apply -auto-approve tfplan

    deploy-to-s3:
        name: Deploy to S3
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1

            - name: Sync files to S3
              run: aws s3 sync ./core s3://final-aws-project/files/
